# Generated by Django 2.2.2 on 2020-01-08 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('billimage', models.ImageField(blank=True, default='bill/no.png', upload_to='bill/')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('Spent', 'Spent'), ('Deposited', 'Deposited')], max_length=10)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('creater', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('deposited', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
